name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name:  run a one line script
        run: echo Avani Dubey
      - name: run a multi line script
        run: |
          echo Awadh Prajapat
          echo Avani Dubey
      
 
